server {
    listen       8080;
    server_name  https://thub-web-2-0-0-378678297066.us-central1.run.app;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }
}
