server {
    listen       8080;
    server_name  https://https://thub-web.happytree-73f6fdda.westus2.azurecontainerapps.io;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }
}
