server {
    listen 8080;
    server_name https://thub-web-2-0-0-378678297066.us-central1.run.app;  # Replace with your domain or IP address

    root /home/gs/THub-web-2.0.0/dist;  # Path to your built Vite app

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
        expires max;
        log_not_found off;
    }
}
