export const pricingData = {
  monthly: [
    {
      title: "Free",
      prices: {
        INR: "₹ 0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters to explore and integrate",
      buttonInfo: "Start for Free",
      list: [
        "Single Seat",
        "5 GenAI Apps",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Bring your own API key",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro",
      prices: {
        INR: "₹ 19,999",
        USD: "$199",
        GBP: "£159",
        Euro: "€189",
      },
      description: "For small & medium businesses",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 Seats",
        "25 GenAI Apps",
        "Team collaboration",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact for Price",
        USD: "Contact for Price",
        GBP: "Contact for Price",
        Euro: "Contact for Price",
      },
      description: "For large teams and enterprises.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Seats", "Unlimited GenAI Apps"],
    },
  ],
  yearly: [
    {
      title: "Free",
      prices: {
        INR: "₹ 0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters to explore and integrate",
      buttonInfo: "Start for Free",
      list: [
        "Single Seat",
        "5 GenAI Apps",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Shared or your own API keys",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro",
      prices: {
        INR: "₹ 2,19,999",
        USD: "$2,199",
        GBP: "£1,699",
        Euro: "€2,099",
      },
      description: "For small & medium businesses",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 Seats",
        "25 GenAI Apps",
        "Team collaboration",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact for Price",
        USD: "Contact for Price",
        GBP: "Contact for Price",
        Euro: "Contact for Price",
      },
      description: "For large teams and enterprises.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Seats", "Unlimited GenAI Apps"],
    },
  ],
};
