export const pricingData = {
  monthly: [
    {
      title: "Free",
      prices: {
        INR: "₹0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters to explore and integrate",
      buttonInfo: "Start for Free",
      list: [
        "Single User",
        "3 Agents",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Bring your own API key",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro",
      prices: {
        INR: "₹ 19,999",
        USD: "$199",
        GBP: "£159",
        Euro: "€189",
      },
      extraPrice: {
        INR: "₹17,999",
        USD: "$229",
        GBP: "£184",
        Euro: "€220",
      },
      description: "For small & medium businesses",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 Users",
        "25 Agents",
        "₹ 17,999/per Additional Agents",
        "Team collaboration",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact for Price",
        USD: "Contact for Price",
        GBP: "Contact for Price",
        Euro: "Contact for Price",
      },
      description: "For large teams and enterprises.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Users", "Unlimited Agents"],
    },
  ],
  yearly: [
    {
      title: "Free",
      prices: {
        INR: "₹ 0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters to explore and integrate",
      buttonInfo: "Start for Free",
      list: [
        "Single User",
        "5 Agents",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Shared or your own API keys",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro",
      prices: {
        INR: "₹ 2,19,999",
        USD: "$2,518",
        GBP: "£2,021",
        Euro: "€2,422",
      },
      extraPrice: {
        INR: "₹1,99,999",
        USD: "$2,288",
        GBP: "£1,837",
        Euro: "€2,203",
      },
      description: "For small & medium businesses",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 User",
        "25 Agents",
        "Team collaboration",
        "₹ 17,999/per Additional Agents",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact for Price",
        USD: "Contact for Price",
        GBP: "Contact for Price",
        Euro: "Contact for Price",
      },
      description: "For large teams and enterprises.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Users", "Unlimited Agents"],
    },
  ],
};
