export const pricingData = {
  monthly: [
    {
      title: "Free Forever",
      prices: {
        INR: "₹0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters: one user, 3 agents, endless potential.",
      buttonInfo: "Start Free",
      list: [
        "Single User",
        "3 Agents",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Bring your own API key",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro Power",
      prices: {
        INR: "₹ 19,999",
        USD: "$199",
        GBP: "£159",
        Euro: "€189",
      },
      extraPrice: {
        INR: "₹17,999",
        USD: "$169",
        GBP: "£149",
        Euro: "€159",
      },
      description: "For teams: 5 users, 10 agents, tools to scale.",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 Users",
        "10 Agents",
        "Team collaboration",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact Us",
        USD: "Contact Us",
        GBP: "Contact Us",
        Euro: "Contact Us",
      },
      description: "For giants: unlimited users, unlimited possibilities.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Users", "Unlimited Agents"],
    },
  ],
  yearly: [
    {
      title: "Free Forever",
      prices: {
        INR: "₹ 0",
        USD: "$0",
        GBP: "£0",
        Euro: "€0",
      },
      description: "For starters: one user, 3 agents, endless potential.",
      buttonInfo: "Start for Free",
      list: [
        "Single User",
        "5 Agents",
        "API based access to LLM",
        "Embedding Model",
        "Vector Database",
        "Shared or your own API keys",
        "Basic Analytics",
        "Standard Support",
      ],
    },
    {
      title: "Pro Power",
      prices: {
        INR: "₹ 2,19,999",
        USD: "$2,518",
        GBP: "£2,021",
        Euro: "€2,422",
      },
      extraPrice: {
        INR: "₹1,99,999",
        USD: "$1,999",
        GBP: "£1,599",
        Euro: "€1,899",
      },
      description: "For teams: 5 users, 10 agents, tools to scale.",
      buttonInfo: "Choose Plan",
      list: [
        "All Free Features",
        "5 User",
        "10 Agents",
        "Team collaboration",
        "₹ 17,999/per Additional Agents",
        "Train your own local LLM",
        "Fine Tune open source LLM",
        "Advanced Analytics",
        "Priority support",
      ],
    },
    {
      title: "Enterprise",
      prices: {
        INR: "Contact for Price",
        USD: "Contact for Price",
        GBP: "Contact for Price",
        Euro: "Contact for Price",
      },
      description: "For giants: unlimited users, unlimited possibilities.",
      buttonInfo: "Get in Touch",
      list: ["All Pro Features", "Unlimited Users", "Unlimited Agents"],
    },
  ],
};
