name: Azure Container Apps Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: 'Login via Service Principal'
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and deploy Container App
              uses: azure/container-apps-deploy-action@v1
              with:
                  appSourcePath: ${{ github.workspace }}
                  acrName: ca7a4dd637e6acr
                  containerAppName: thub-web
                  resourceGroup: gs_rg_0361
