name: Trigger auto deployment for thub-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/thub-web-AutoDeployTrigger-1a16c064-30b0-47b1-a096-773392496a3c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.THUBWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.THUBWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.THUBWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.THUBWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.THUBWEB_REGISTRY_PASSWORD }}
          containerAppName: thub-web
          resourceGroup: gs_rg_0361
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


